baseURL = "https://pal3dreamer.github.io/"
languageCode = "en-us"
title = "paledreamer's Blog"
theme="archie"
copyright = "© paledreamer"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=true
	subtitle = "CTF writeups and blog posts"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pal3dreamer"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
[[menu.main]]
name = "Writeups"
url = "/writeups"
weight = 2
// [[menu.main]]
// name = "About"
//url = "/about"
//weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


